#!/usr/bin/env python3
# Parses tbl_noticias INSERT statements out of the 2020 MySQL dump (no mysql
# client available locally) and cross-references titles against the current
# live blog (MAPA-CONTEUDO-BLOG.csv, already generated by the SEO audit
# crawler) to find which posts could get a real recovered image instead of
# the generic Mclair fallback cover.
import re
import csv
import os
import unicodedata
from difflib import SequenceMatcher

DUMP = os.path.expanduser('~/Downloads/2020/mclair_1.sql')
GALERIA_DIR = os.path.expanduser('~/Downloads/2020/images/galeria')
BLOG_MAP_CSV = '/Users/macbook/mclair/MAPA-CONTEUDO-BLOG.csv'
OUT_CSV = '/Users/macbook/mclair/audit-out/IMAGENS-2020-RECUPERAVEIS.csv'

COLUMNS = ['cod_noticia', 'categoria_noticia', 'idioma_noticia', 'titulo_noticia',
           'data_criacao', 'horario_criacao', 'fonte_nome', 'fonte_link',
           'thumbnail_noticia', 'corpo_noticia', 'destino_sistema', 'destaque_noticia',
           'subtitulo_noticia', 'edicao_noticia', 'ano_edicao', 'status_noticia',
           'ultima_alteracao', 'aprovada_por', 'rejeitada_por', 'CriadaPor']


def parse_values_blob(blob):
    """Tokenize a MySQL VALUES (...),(...),(...); blob into a list of row tuples,
    each a list of raw field strings (still SQL-quoted/escaped)."""
    rows = []
    i = 0
    n = len(blob)
    while i < n:
        while i < n and blob[i] in ' \n\t,':
            i += 1
        if i >= n or blob[i] != '(':
            break
        i += 1  # skip (
        fields = []
        buf = []
        depth = 1
        while i < n and depth > 0:
            c = blob[i]
            if c == "'":
                buf.append(c)
                i += 1
                while i < n:
                    if blob[i] == '\\' and i + 1 < n:
                        buf.append(blob[i]); buf.append(blob[i+1])
                        i += 2
                        continue
                    if blob[i] == "'":
                        buf.append(blob[i])
                        i += 1
                        break
                    buf.append(blob[i])
                    i += 1
                continue
            if c == '(':
                depth += 1
                buf.append(c); i += 1; continue
            if c == ')':
                depth -= 1
                if depth == 0:
                    fields.append(''.join(buf))
                    i += 1
                    break
                buf.append(c); i += 1; continue
            if c == ',' and depth == 1:
                fields.append(''.join(buf))
                buf = []
                i += 1
                continue
            buf.append(c)
            i += 1
        rows.append(fields)
    return rows


def unquote(s):
    s = s.strip()
    if s == 'NULL':
        return None
    if s.startswith("'") and s.endswith("'"):
        s = s[1:-1]
        s = s.replace("\\'", "'").replace('\\"', '"').replace('\\\\', '\\').replace('\\r', '\r').replace('\\n', '\n')
        return s
    return s


def norm_title(t):
    t = unicodedata.normalize('NFD', t or '')
    t = ''.join(c for c in t if unicodedata.category(c) != 'Mn')
    t = re.sub(r'[^a-z0-9 ]', ' ', t.lower())
    t = re.sub(r'\s+', ' ', t).strip()
    return t


with open(DUMP, encoding='utf-8', errors='replace') as f:
    dump = f.read()

records = []
for m in re.finditer(r"INSERT INTO `tbl_noticias` \([^)]*\) VALUES\n?(.*?);\n", dump, re.S):
    blob = m.group(1)
    for fields in parse_values_blob(blob):
        if len(fields) != len(COLUMNS):
            continue
        row = dict(zip(COLUMNS, [unquote(x) for x in fields]))
        records.append(row)

print(f'parsed {len(records)} rows from tbl_noticias')

# which thumbnail files actually exist locally in the 2020 backup
existing_files = set(os.listdir(GALERIA_DIR)) if os.path.isdir(GALERIA_DIR) else set()
print(f'{len(existing_files)} files present in local images/galeria backup')

usable = []
for r in records:
    thumb = r.get('thumbnail_noticia') or ''
    fname = thumb.rsplit('/', 1)[-1] if thumb else ''
    local_exists = fname in existing_files
    if thumb and '/images/galeria/' in thumb and local_exists:
        usable.append(r)

print(f'{len(usable)} old posts have a thumbnail AND the file exists locally')

# cross-reference with current blog
with open(BLOG_MAP_CSV, encoding='utf-8') as f:
    current_posts = list(csv.DictReader(f))
current_by_norm = {}
for p in current_posts:
    key = norm_title(p['Title'].split('|')[0].split(',')[0])
    current_by_norm.setdefault(key, []).append(p)

matches = []
for r in usable:
    old_title_norm = norm_title(r['titulo_noticia'])
    best = None
    best_score = 0.0
    for p in current_posts:
        cur_norm = norm_title(p['Title'].split('|')[0].split(',')[0])
        score = SequenceMatcher(None, old_title_norm, cur_norm).ratio()
        if score > best_score:
            best_score = score
            best = p
    matches.append({
        'cod_noticia': r['cod_noticia'],
        'titulo_2020': r['titulo_noticia'],
        'data_2020': r['data_criacao'],
        'thumbnail_2020': r['thumbnail_noticia'],
        'melhor_match_url_atual': best['URL'] if best else '',
        'melhor_match_title_atual': best['Title'] if best else '',
        'similaridade': round(best_score, 3) if best else 0,
    })

matches.sort(key=lambda x: -x['similaridade'])
os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
with open(OUT_CSV, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=list(matches[0].keys()) if matches else [])
    w.writeheader()
    w.writerows(matches)

high_conf = [m for m in matches if m['similaridade'] >= 0.75]
med_conf = [m for m in matches if 0.5 <= m['similaridade'] < 0.75]
print(f'wrote {OUT_CSV} ({len(matches)} rows)')
print(f'alta confianca (>=0.75 similaridade de titulo): {len(high_conf)}')
print(f'media confianca (0.50-0.75): {len(med_conf)}')
print(f'baixa/sem match confiavel: {len(matches) - len(high_conf) - len(med_conf)}')
